name: Build Dylib

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile 1 - With Vibration (LeftPanVib.dylib)
        run: |
          xcrun -sdk iphoneos clang -arch arm64 -shared -fobjc-arc \
            -Os -fvisibility=hidden -Wl,-x -Wl,-S \
            -target arm64-apple-ios14.0 \
            -miphoneos-version-min=14.0 \
            -install_name @rpath/LeftPanVib.dylib \
            -framework UIKit -framework Foundation \
            leftPan_vib.m -o LeftPanVib.dylib
          codesign -f -s - LeftPanVib.dylib

      - name: Compile 2 - Without Vibration (LeftPanWithoutVib.dylib)
        run: |
          xcrun -sdk iphoneos clang -arch arm64 -shared -fobjc-arc \
            -Os -fvisibility=hidden -Wl,-x -Wl,-S \
            -target arm64-apple-ios14.0 \
            -miphoneos-version-min=14.0 \
            -DDISABLE_VIBRATION \
            -install_name @rpath/LeftPanWithoutVib.dylib \
            -framework UIKit -framework Foundation \
            leftPan_vib.m -o LeftPanWithoutVib.dylib
          codesign -f -s - LeftPanWithoutVib.dylib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LeftPan_Release_Package
          path: |
            LeftPanVib.dylib
            LeftPanWithoutVib.dylib
